### ISSUE TITLE
Large avatar image on profile pages is not replaced

### ISSUE THREAD

**Issue by i336** [leftshift/github-all-cats#7]
Viewing the profile page of a user shows the avatar they've set, and doesn't replace it with one of the images bundled in the extension.

Perhaps this is due to a recent change.

**Comment by leftshift** [comment]
Actually, quite a few things seem to have broken recently… I'll see what I can do
- [ ] Avatar on profile page
- [ ] Avatar and Name when hovering over a username
- [ ] Names in Issue list
- [ ] link to latest commit on repository overview
